DBfirst-2106/Controllers/EnrollCoursesController.cs
using DBfirst_2106.Data;
using DBfirst_2106.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace DBfirst_2106.Controllers
{
    public class EnrollCoursesController : Controller
    {
        private readonly DbfirstContext _context;

        public EnrollCoursesController(DbfirstContext context)
        {
            _context = context;
        }

        // GET: EnrollCourses
        public async Task<IActionResult> Index()
        {
            var dbfirstContext = _context.StuEnrollCourses.Include(s => s.Course).Include(s => s.SIdNavigation);
            return View(await dbfirstContext.ToListAsync());
        }

        // GET: EnrollCourses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.StuEnrollCourses == null)
            {
                return NotFound();
            }

            var stuEnrollCourse = await _context.StuEnrollCourses
                .Include(s => s.Course)
                .Include(s => s.SIdNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (stuEnrollCourse == null)
            {
                return NotFound();
            }

            return View(stuEnrollCourse);
        }

        // GET: EnrollCourses/Create
        public IActionResult Create()
        {
            ViewData["Courseid"] = new SelectList(_context.Courses, "Courseid", "Courseid");
            ViewData["SId"] = new SelectList(_context.Student1s, "SId", "SId");
            return View();
        }

        // POST: EnrollCourses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SId,Courseid,Grade,Id")] StuEnrollCourse stuEnrollCourse)
        {
            if (ModelState.IsValid)
            {
                _context.Add(stuEnrollCourse);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Courseid"] = new SelectList(_context.Courses, "Courseid", "Courseid", stuEnrollCourse.Courseid);
            ViewData["SId"] = new SelectList(_context.Student1s, "SId", "SId", stuEnrollCourse.SId);
            return View(stuEnrollCourse);
        }

        // GET: EnrollCourses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.StuEnrollCourses == null)
            {
                return NotFound();
            }

            var stuEnrollCourse = await _context.StuEnrollCourses.FindAsync(id);
            if (stuEnrollCourse == null)
            {
                return NotFound();
            }
            ViewData["Courseid"] = new SelectList(_context.Courses, "Courseid", "Courseid", stuEnrollCourse.Courseid);
            ViewData["SId"] = new SelectList(_context.Student1s, "SId", "SId", stuEnrollCourse.SId);
            return View(stuEnrollCourse);
        }

        // POST: EnrollCourses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SId,Courseid,Grade,Id")] StuEnrollCourse stuEnrollCourse)
        {
            if (id != stuEnrollCourse.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(stuEnrollCourse);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StuEnrollCourseExists(stuEnrollCourse.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Courseid"] = new SelectList(_context.Courses, "Courseid", "Courseid", stuEnrollCourse.Courseid);
            ViewData["SId"] = new SelectList(_context.Student1s, "SId", "SId", stuEnrollCourse.SId);
            return View(stuEnrollCourse);
        }

        // GET: EnrollCourses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.StuEnrollCourses == null)
            {
                return NotFound();
            }

            var stuEnrollCourse = await _context.StuEnrollCourses
                .Include(s => s.Course)
                .Include(s => s.SIdNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (stuEnrollCourse == null)
            {
                return NotFound();
            }

            return View(stuEnrollCourse);
        }

        // POST: EnrollCourses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.StuEnrollCourses == null)
            {
                return Problem("Entity set 'DbfirstContext.StuEnrollCourses'  is null.");
            }
            var stuEnrollCourse = await _context.StuEnrollCourses.FindAsync(id);
            if (stuEnrollCourse != null)
            {
                _context.StuEnrollCourses.Remove(stuEnrollCourse);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StuEnrollCourseExists(int id)
        {
            return (_context.StuEnrollCourses?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        public IActionResult courseandprof()
        {
            return View();
        }
        [HttpPost]
        public IActionResult courseandprofSearch(string course, string prof)
        {
            var x = _context.TauCourses
                .Include(s => s.Course)
                .Include(s => s.PIdNavigation)
                .Where(e => e.PIdNavigation.PName == prof).Select(e => e).ToList();

            var obj = _context.StuEnrollCourses
                .Include(s => s.Course)
                .Include(s => s.SIdNavigation)
                .Where(e => e.Course.Coursename == course).Select(e => e).ToList();



            if (x != null && obj != null)
                return View();

            return NotFound();
        }

        public IActionResult topperformersdept()
        {
            var obj = _context.Student1s
                 .Select(e => e.SDept).Distinct().ToList();
            ViewBag.list1 = obj;
            return View();
        }
        [HttpPost]
        public IActionResult topperformersdeptSearch(string dept)
        {


            var obj = _context.StuEnrollCourses
                .Include(s => s.Course)
                .Include(s => s.SIdNavigation)
                .Where(x => x.SIdNavigation.SDept == dept)
                .OrderByDescending(x => x.Grade)
                .Take(5)
                .ToList();
            return View(obj);
        }

        public IActionResult topperformerscourse()
        {
            var obj = _context.Courses
                 .Select(e => e.Courseid).ToList();
            ViewBag.list = obj;
            return View();
        }
        [HttpPost]
        public IActionResult topperformerscourseSearch(int courseid)
        {
            var obj = _context.StuEnrollCourses
                .Include(s => s.Course)
                .Include(s => s.SIdNavigation)
                .Where(x => x.Courseid == courseid)
                .OrderByDescending(x => x.Grade)
                .Take(5)
                .ToList();
            return View(obj);
        }

        public IActionResult studentsincourse()
        {


            ViewData["Pid"] = new SelectList(_context.Professors, "PId", "PName");
            ViewData["Courseid"] = new SelectList(_context.Courses, "Courseid", "Coursename");

            var obj = _context.Professors.Select(x => x.PId).ToList();
            ViewBag.Pidlist = obj;

            var obj2 = _context.Courses.Select(x => x.Courseid).ToList();
            ViewBag.Courseidlist = obj2;


            return View();
        }


        [HttpPost]
        public IActionResult studentsincourseSearch(int courseid, int prof)
        {


            var obj = _context.StuEnrollCourses
                .Include(s => s.Course)
                .Include(s => s.SIdNavigation)
                .Where(x => x.Courseid == courseid).
                ToList();

            var obj2 = _context.TauCourses
                .Include(s => s.Course)
                .Include(s => s.PIdNavigation)
                .Where(s => s.PIdNavigation.PId == prof)
                .Where(x => x.Courseid == courseid)
                .ToList();




            if (obj2.Count == 0 || obj.Count == 0)
            {
                return this.NotFound("No Such Records Found");
            }


            VM1 model = new VM1();
            model.Courseids = obj;
            model.Profs = obj2;

            return View(model);

        }


        public JsonResult GetProfs(string term)
        {
            List<string> profs;

            profs = _context.Professors.Select(x => x.PName).ToList();

            return Json(profs);
        }
    }
}

DBfirst-2106/Views/EnrollCourses/Create.cshtml
@model DBfirst_2106.Models.StuEnrollCourse

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>StuEnrollCourse</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SId" class="control-label"></label>
                <select asp-for="SId" class ="form-control" asp-items="ViewBag.SId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Courseid" class="control-label"></label>
                <select asp-for="Courseid" class ="form-control" asp-items="ViewBag.Courseid"></select>
            </div>
            <div class="form-group">
                <label asp-for="Grade" class="control-label"></label>
                <input asp-for="Grade" class="form-control" />
                <span asp-validation-for="Grade" class="text-danger"></span>
            </div>
            <p>

            </p>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" /> 
            </div>
        </form>
    </div>
</div>
<p>

</p>
<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

DBfirst-2106/Views/EnrollCourses/Delete.cshtml
@model DBfirst_2106.Models.StuEnrollCourse

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>StuEnrollCourse</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Grade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Grade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Course.Courseid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SIdNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SIdNavigation.SId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DBfirst-2106/Views/EnrollCourses/Details.cshtml
@model DBfirst_2106.Models.StuEnrollCourse

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>StuEnrollCourse</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Grade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Grade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Course.Courseid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SIdNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SIdNavigation.SId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DBfirst-2106/Views/EnrollCourses/Edit.cshtml
@model DBfirst_2106.Models.StuEnrollCourse

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>StuEnrollCourse</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SId" class="control-label"></label>
                <select asp-for="SId" class="form-control" asp-items="ViewBag.SId"></select>
                <span asp-validation-for="SId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Courseid" class="control-label"></label>
                <select asp-for="Courseid" class="form-control" asp-items="ViewBag.Courseid"></select>
                <span asp-validation-for="Courseid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Grade" class="control-label"></label>
                <input asp-for="Grade" class="form-control" />
                <span asp-validation-for="Grade" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

DBfirst-2106/Views/EnrollCourses/Index.cshtml
@model IEnumerable<DBfirst_2106.Models.StuEnrollCourse>

@{
    ViewData["Title"] = "Index";
}


<p>

</p>

<p>
    <a asp-action="Create"  class ="btn btn-primary ">Add New</a>
</p>


<div>
    <table class="border-0">
        <tr>
            <h3>Search here</h3>
        </tr>
        <tr>
            <td class="ml-3">
                <a asp-action="topperformerscourse" class="btn btn-outline-warning"><i class="bi bi-search"></i> Find top Students Course wise </a>
            </td>
            <td>
                |
            </td>
             <td class="ml-3">
               <a asp-action="topperformersdept" class="btn btn-outline-warning"><i class="bi bi-search"></i> Find top Students Department wise </a>
            </td>
            <td>
                |
            </td>
             <td class="ml-3">
                 <a asp-action="studentsincourse" class="btn btn-outline-warning"><i class="bi bi-search"></i> Find Students taught by specific Professor </a>
            </td>
        </tr>
    </table>
</div>

<hr />



<table class="table tabel-hover">
    <thead class="table-info">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SIdNavigation.SId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SIdNavigation.SDept)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Courseid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Course)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Grade)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            
            
            <td>
                @Html.DisplayFor(modelItem => item.SIdNavigation.SId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SIdNavigation.SDept)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Course.Courseid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Course.Coursename)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Grade)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-secondary">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info">Details</a> 
               @* <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>*@
            </td>
        </tr>
}
    </tbody>
</table>

DBfirst-2106/Views/EnrollCourses/studentsincourse.cshtml
@model DBfirst_2106.Models.StuEnrollCourse


<script src ="~/lib/jquery/dist/jquery.js"></script>
<script
  src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"
  integrity="sha256-6XMVI0zB8cRzfZjqKcD01PBsAy3FlDASrlC8SxCpInY="
  crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js" integrity="sha256-eTyxS0rkjpLEo16uXTS0uVCS4815lc40K2iVpWDvdSY=" crossorigin="anonymous"></script>


<script type="text/javascript">
    $(function(){
        $("#prof1").change(function(){
            var profs = $("#prof1 Option:selected").val();
            $("#txtprof").val(profs);
        })
    });
</script>


@{
    ViewData["Title"] = "studentsincourse";
}

<h1>studentsincourse</h1>

<div class="row">
    <div class="col-md-4">
        @using(Html.BeginForm("studentsincourseSearch","EnrollCourses"))
        {
           
             <label  class="control-label">Course Code    </label><br />
             <select asp-for="Courseid" class ="form-control" asp-items="ViewBag.Courseid">
                 <option value="" disabled selected hidden>Select Course</option>
             </select>
            <br /><br />
            <div>
                <label id="Taught By" class="control-label">Taught by      </label><br/>
                

                <input hidden type="text" id="txtprof" name="prof"/>
                 <select id="prof1" class ="form-control" asp-items="ViewBag.Pid">
                     <option value="" disabled selected hidden>Select Professor</option>
                </select>
             </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        }
    </div>
</div>

<div>
   
    <a asp-action="Index">Back to List</a>
</div>

DBfirst-2106/Views/EnrollCourses/studentsincourseSearch.cshtml
@using DBfirst_2106.Models

@model VM1

@{
    ViewData["Title"] = "studentsincourseSearch";
}

@if (Model == null)
{
    <h1>No Matching Results Found</h1>
}

@*<h3>Taught by Professor @Model.Profs</h3>*@

<table class="table">
    <thead>
        <tr>
            <th>
                @*@Html.DisplayNameFor(model => model.Courseids)*@
                Course Code
            </th>
            <th>
               @* @Html.DisplayNameFor(model => model.Profs)*@
               Roll No
            </th>
           @* <th>
                @Html.DisplayNameFor(model => model.SIdNavigation.SId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SIdNavigation.SDept)
            </th>*@
            <th>
               @* @Html.DisplayNameFor(model => model.Profs)*@
               Student Name
            </th>
           <th>
               @* @Html.DisplayNameFor(model => model.Profs)*@
               Student Department
            </th>
            <th>Professor</th>

            @*<th>
               @* @Html.DisplayNameFor(model => model.Profs)
               ID
            </th>
            <th>
               @Html.DisplayNameFor(model => model.Profs)
               Department
            </th>*@
           @* <th></th>*@
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
@foreach (var item in Model.Courseids) {
        <tr>
           
            <td>
                @Html.DisplayFor(modelItem => item.Course.Courseid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SIdNavigation.SId)
            </td>
             <td>
                @Html.DisplayFor(modelItem => item.SIdNavigation.SName)
            </td>
             <td>
                @Html.DisplayFor(modelItem => item.SIdNavigation.SDept)
            </td>
             
           @* <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>*@
                        @foreach(var x in Model.Profs)
                        {
                            <td>
                @Html.DisplayFor(modelItem => x.PIdNavigation.PName)
            </td>
                        }
                    </tr>
}
            </td>
<td>
@*@foreach (var item in Model.Profs) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PIdNavigation.PName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PIdNavigation.PId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PIdNavigation.PDept)
            </td>
             @*<td>
                @Html.DisplayFor(modelItem => item.SIdNavigation.SDept)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}*@
        </td>
       </tr>
    </tbody>
</table>
<div>
   
    <a asp-action="studentsincourse">Back to Search</a>
</div>

DBfirst-2106/Views/EnrollCourses/topperformerscourse.cshtml
@model DBfirst_2106.Models.StuEnrollCourse;

@{
    ViewData["Title"] = "topperformers";
}

<h1>top performers</h1>

<div class="row">
    <div class="col-md-4">
        @using(Html.BeginForm("topperformerscourseSearch","EnrollCourses"))
        {
            @Html.DropDownListFor(e=>e.Courseid,new SelectList(ViewBag.list),"Select Course",new{@class="form-control"})
            @*<div class="form-group">
                <label asp-for="Course.Courseid" class="control-label"></label>
                
                <input type="text" name="courseid"/><br/>
                <span asp-validation-for="Course.Courseid" class="text-danger"></span>
            </div>*@


            @*<div class="form-group">
                <label asp-for="SIdNavigation.SDept" class="control-label"></label>
                <input type="text" name="dept"/><br/>
               <span asp-validation-for="PName" class="text-danger"></span>*
          </div>*@
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        }
    </div>
</div>

<div>
   
    <a asp-action="Index">Back to List</a>
</div>

DBfirst-2106/Views/EnrollCourses/topperformerscourseSearch.cshtml
@model IEnumerable<DBfirst_2106.Models.StuEnrollCourse>

@{
    ViewData["Title"] = "topperformersSearch";
}

<h1>topperformersSearch</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Grade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Course)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SIdNavigation.SId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SIdNavigation.SDept)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Grade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Course.Courseid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SIdNavigation.SId)
            </td>
             <td>
                @Html.DisplayFor(modelItem => item.SIdNavigation.SDept)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

<div>
   
    <a asp-action="Index">Back to List</a>
</div>

DBfirst-2106/Views/EnrollCourses/topperformersdept.cshtml
@model DBfirst_2106.Models.StuEnrollCourse;


<script src ="~/lib/jquery/dist/jquery.js"></script>
<script
  src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"
  integrity="sha256-6XMVI0zB8cRzfZjqKcD01PBsAy3FlDASrlC8SxCpInY="
  crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js" integrity="sha256-eTyxS0rkjpLEo16uXTS0uVCS4815lc40K2iVpWDvdSY=" crossorigin="anonymous"></script>


<script type="text/javascript">
    $(function(){
        $("#dept1").change(function(){
            var depts = $("#dept1 Option:selected").val();
            $("#txtdept").val(depts);
        })
    });
</script>

@{
    ViewData["Title"] = "topperformers";
}

<h1>top performers</h1>

<div class="row">
    <div class="col-md-4">
        @using(Html.BeginForm("topperformersdeptSearch","EnrollCourses"))
        {
             <div>
                <label  class="control-label">Department      </label><br/>
                

                <input hidden type="text" id="txtdept" name="dept"/>
                 <select id="dept1" class ="form-control" asp-items="new SelectList(ViewBag.list1)">
                     <option value="" disabled selected hidden>Select Department</option>
                </select>
             </div>

            

             

           
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        }
    </div>
</div>

<div>
   
    <a asp-action="Index">Back to List</a>
</div>

DBfirst-2106/Views/EnrollCourses/topperformersdeptSearch.cshtml
@model IEnumerable<DBfirst_2106.Models.StuEnrollCourse>

@{
    ViewData["Title"] = "topperformersSearch";
}

<h1>topperformersSearch</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Grade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Course)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SIdNavigation.SId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SIdNavigation.SDept)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Grade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Course.Courseid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SIdNavigation.SId)
            </td>
             <td>
                @Html.DisplayFor(modelItem => item.SIdNavigation.SDept)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

<div>
   
    <a asp-action="Index">Back to List</a>
</div>